-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:b2eafcc24ae0464e25c48dc570583786$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "AntWalkSpriteSheet-1.png",
				spriteColorRect = { x = 66, y = 37, width = 62, height = 52 },
				textureRect = { x = 2, y = 2, width = 62, height = 52 },
				spriteSourceSize = { width = 192, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "AntWalkSpriteSheet-2.png",
				spriteColorRect = { x = 66, y = 39, width = 62, height = 48 },
				textureRect = { x = 66, y = 2, width = 62, height = 48 },
				spriteSourceSize = { width = 192, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "AntWalkSpriteSheet-3.png",
				spriteColorRect = { x = 65, y = 37, width = 62, height = 50 },
				textureRect = { x = 130, y = 2, width = 62, height = 50 },
				spriteSourceSize = { width = 192, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "AntWalkSpriteSheet-4.png",
				spriteColorRect = { x = 64, y = 40, width = 62, height = 50 },
				textureRect = { x = 2, y = 56, width = 62, height = 50 },
				spriteSourceSize = { width = 192, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "AntWalkSpriteSheet-5.png",
				spriteColorRect = { x = 65, y = 39, width = 62, height = 50 },
				textureRect = { x = 66, y = 56, width = 62, height = 50 },
				spriteSourceSize = { width = 192, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "AntWalkSpriteSheet-6.png",
				spriteColorRect = { x = 66, y = 40, width = 62, height = 50 },
				textureRect = { x = 130, y = 56, width = 62, height = 50 },
				spriteSourceSize = { width = 192, height = 128 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

